blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/OnChainDiscGolf/app/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“š Documentation
    url: https://help.onchaindiscgolf.com
    about: Check out our documentation for guides and FAQs

